name: PGSA_FinalAssignment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - notebook=5.7
  - rasterio=1.0
  - matplotlib=3.0
  - pandas=0.24
  - geopandas=0.5
  - pysal=2.0
  - dill=0.2
